import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "@nextui-org/react/button";
import { Container, Row, Card, theme, Text } from "@nextui-org/react";
import { useTheme as useNextTheme } from "next-themes";
import { Switch, useTheme } from "@nextui-org/react";
import ContentPage from "./contentPage";

export default function Home() {
  const { setTheme } = useNextTheme();
  const { isDark, type, theme } = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
      </Head>
      <div className={styles.container}>
        <header
          style={{
            backgroundColor: isDark
              ? theme.colors.purple400.value
              : theme.colors.blue600.value,
          }}
        >
          <div className={styles.header}>
            <Row
              style={{
                justifyContent: "space-between",
              }}
            >
              <Text
                className={styles.hearder_title}
                style={{
                  backgroundColor: "#fff",
                }}
              >
                {" "}
                Whett
              </Text>
              <Switch
                style={{
                  alignSelf: "center",
                }}
                color={"secondary"}
                checked={isDark}
                iconOn={<i className="bx bx-moon" />}
                iconOff={<i className="bx bx-sun" />}
                onChange={(e) => setTheme(e.target.checked ? "dark" : "light")}
              />
            </Row>
          </div>
        </header>
        <ContentPage props={"yyyssss"} test={"aaaa"} />

        <footer className={styles.footer}>
          <p>Dev by Ratchanon Pheungta</p>
          <a
            href="https://www.linkedin.com/in/ratchanon-pheungta-6846a9229/"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.social_icon}
          >
            <i className="bx bxl-linkedin-square"></i>
          </a>
        </footer>
      </div>
    </>
  );
}
